# This is a GitHub workflow defining a set of jobs with a set of steps.
# ref: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
#
name: Tests

on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - ".github/workflows/*.yaml"
      - "!.github/workflows/test.yaml"
  push:
    paths-ignore:
      - "docs/**"
      - ".github/workflows/*.yaml"
      - "!.github/workflows/test.yaml"
    branches-ignore:
      - "dependabot/**"
      - "pre-commit-ci-update-config"
    tags: ["**"]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        include:
          # oldest supported python and jupyterhub version
          - python-version: "3.7"
            jupyterhub-version: "1.3.0"

          - python-version: "3.8"
            jupyterhub-version: "1.*"
          - python-version: "3.9"
            jupyterhub-version: "2.*"
          - python-version: "3.10"
            jupyterhub-version: "3.*"
          - python-version: "3.11"
            jupyterhub-version: "4.*"

          # latest version of python and jupyterhub (including pre-releases)
          - python-version: "3.x"
            jupyterhub-version: "*"
            pip-install-flags: --pre

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "${{ matrix.python-version }}"

      - name: Install Python dependencies
        run: |
          pip install ${{ matrix.pip-install-flags }} "jupyterhub==${{ matrix.jupyterhub-version }}"
          pip install ".[test]"
          pip freeze

      - name: Run tests
        run: |
          pytest --cov=jupyterhub-tmpauthenticator

      - uses: codecov/codecov-action@v3
